spring.application.name=cognitive-vault

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5434/cognitive_vault
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL Initialization
spring.sql.init.mode=always

# AWS SDK / MinIO S3 Configuration
aws.region=us-east-1
aws.access-key=minioadmin
aws.secret-key=minioadmin
aws.s3.endpoint=http://localhost:9000
aws.s3.bucket=cognitive-vault-attachments
